namespace Infrastructure.Communication
{
    public enum Operation
    {
        AuthLogin,
        AuthLogout,
        BooksFindAll,
        BooksFindOne,
        BooksCreate,
        BooksUpdate,
        BooksDelete,
        BookCopiesFindAll,
        BookCopiesFindOne,
        BookCopiesCreate,
        BookCopiesUpdate,
        BookCopiesDelete,
        CustomersFindAll,
        CustomersFindOne,
        CustomersCreate,
        CustomersUpdate,
        CustomersDelete,
        EmployeesFindAll,
        EmployeesFindOne,
        EmployeesCreate,
        EmployeesUpdate,
        EmployeesDelete,
        LibrariesFindAll,
        LibrariesFindOne,
        LibrariesCreate,
        LibrariesUpdate,
        LibrariesDelete,
    }
}